"use client"
import React, { useState } from 'react'
import SelectTopic from './_components/selectTopic'
import SelectStyle from './_components/SelectStyle'
import Duration from './_components/selectDuration';
import { Button } from '@/components/ui/button';
import axios from 'axios';
import CustomLoading from './_components/CustomLoading';
import VideoPlayer from '@/components/VideoPlayer';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"

function CreateNew() {

  const [formData, setFormData] = useState({ aiProvider: 'gemini', voiceProvider: 'free' });
  const [loading, setLoading] = useState(false); 
  const [statusText, setStatusText] = useState('');
  const [fullVideoData, setFullVideoData] = useState(null);
  const [alertConfig, setAlertConfig] = useState({ isOpen: false, title: '', message: '', type: 'warning' });

  const showAlert = (title, message, type = 'warning') => {
    setAlertConfig({
      isOpen: true,
      title,
      message,
      type
    });
  }

  const onHandleInputChange = (fieldName, fieldValue) => {
    console.log(fieldName, fieldValue)
    setFormData(prev => ({
      ...prev,
      [fieldName]: fieldValue
    }))
  }

  const generateVideo = async () => {
    // 1. Inputs validation
    if (!formData.duration || !formData.topic || !formData.imageStyle) {
      showAlert("Incomplete Settings", "Please choose a topic, style, and duration first.");
      return;
    }

    // 2. Select model & voice parameters
    const selectedAI = formData.aiProvider || 'gemini';
    const selectedVoice = formData.voiceProvider || 'free';

    // 3. Dynamic Local storage API Keys validation
    let apiKey = '';
    if (selectedAI === 'gemini') {
      apiKey = localStorage.getItem('waffle_gemini_key') || '';
    } else if (selectedAI === 'openai') {
      apiKey = localStorage.getItem('waffle_openai_key') || '';
    } else if (selectedAI === 'anthropic') {
      apiKey = localStorage.getItem('waffle_claude_key') || '';
    }

    if (!apiKey) {
      showAlert(
        "AI Key Missing", 
        `API Key for ${selectedAI.toUpperCase()} is missing! Please click the settings button in the header and configure your credentials.`
      );
      return;
    }

    // Since Anthropic (Claude) does not generate images, ensure we have an image generation key (Gemini or OpenAI)
    const geminiKey = localStorage.getItem('waffle_gemini_key') || '';
    const openaiKey = localStorage.getItem('waffle_openai_key') || '';
    if (!geminiKey && !openaiKey) {
      showAlert(
        "Image Generator Key Missing",
        "An API key for either Gemini (Imagen 3) or OpenAI (DALL-E 3) is required to generate the video artwork. Please configure one in the settings modal."
      );
      return;
    }

    let voiceKey = '';
    if (selectedVoice === 'gcp') {
      voiceKey = localStorage.getItem('waffle_tts_key') || '';
      if (!voiceKey) {
        showAlert(
          "GCP Key Missing",
          "Google Cloud TTS key is missing! Please configure it in settings or choose the Free Voice option."
        );
        return;
      }
    }

    setLoading(true);
    setFullVideoData(null);

    try {
      // Step A: Script Generation
      setStatusText(`Generating script using ${selectedAI.toUpperCase()} AI...`);
      const prompt = `Write a script to generate ${formData.duration} video on topic: ${formData.topic} along with AI image prompt in ${formData.imageStyle} format for each scene and give me result in JSON format with imagePrompt and ContentText as field`;
      
      const scriptResp = await axios.post('/api/get-video-script', 
        { prompt },
        { 
          headers: { 
            'x-ai-provider': selectedAI,
            'x-ai-key': apiKey
          } 
        }
      );

      const scriptData = scriptResp.data.result;
      const scenes = scriptData?.scenes || [];

      if (scenes.length === 0) {
        throw new Error("No scenes generated by the script model. Try a different topic prompt.");
      }

      console.log("Script scenes generated:", scenes);
      const processedScenes = [];

      // Step B: Loop through each scene and call Audio + Image APIs
      for (let i = 0; i < scenes.length; i++) {
        const scene = scenes[i];

        // Synthesize narration
        setStatusText(`[Scene ${i + 1}/${scenes.length}] Synthesizing voiceover (${selectedVoice.toUpperCase()})...`);
        const audioResp = await axios.post('/api/generate-audio',
          { text: scene.ContentText, provider: selectedVoice },
          { headers: { 'x-tts-key': voiceKey } }
        );
        const audioContent = audioResp.data.audioContent;
        const audioBlob = await fetch(`data:audio/mp3;base64,${audioContent}`).then(r => r.blob());
        const audioUrl = URL.createObjectURL(audioBlob);

        // Generate scene visual image
        setStatusText(`[Scene ${i + 1}/${scenes.length}] Creating scene artwork visual...`);
        
        // Detect available image generation provider (prefer Gemini Imagen, fallback to OpenAI DALL-E)
        let imageProvider = 'gemini';
        let imageKey = geminiKey;
        
        if (!geminiKey && openaiKey) {
          imageProvider = 'openai';
          imageKey = openaiKey;
        }

        const imageResp = await axios.post('/api/generate-image',
          { prompt: scene.imagePrompt, style: formData.imageStyle },
          { 
            headers: { 
              'x-image-provider': imageProvider,
              'x-image-key': imageKey 
            } 
          }
        );
        const imageBytes = imageResp.data.imageBytes;
        const imageUrl = `data:image/jpeg;base64,${imageBytes}`;

        processedScenes.push({
          ...scene,
          audioUrl,
          imageUrl
        });
      }

      // Finish and load player
      setFullVideoData({ scenes: processedScenes });
      console.log("Generation complete! Loading player...");

    } catch (error) {
      console.error("Video Generation Error:", error.response?.data || error.message);
      showAlert("Generation Failed", error.response?.data?.Error || error.message, "error");
    } finally {
      setLoading(false);
      setStatusText('');
    }
  }

  const onCreateClickHandler = () => {
    generateVideo();
  }

  return (
   <div className='md:px-20 pb-20'>
      {fullVideoData ? (
        <VideoPlayer videoData={fullVideoData} onBack={() => setFullVideoData(null)} />
      ) : (
        <>
          <div className="flex flex-col items-center justify-center text-center mt-6">
            <h2 className='font-bold text-4xl text-primary'>Create Video</h2>
            <p className="text-gray-500 mt-2">Generate customized video shorts using AI scripts, voices, and artwork</p>
          </div>
          <div className='mt-8 shadow-md rounded-2xl border border-gray-100 bg-white p-8 space-y-7'>
            <SelectTopic onUserSelect={onHandleInputChange}/>
            <SelectStyle onUserSelect={onHandleInputChange}/>
            <Duration onUserSelect={onHandleInputChange}/>

            {/* Model & Voice configuration selectors */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4 border-t border-gray-100">
              <div>
                <label className="block text-sm font-bold text-gray-700 mb-2">AI Model Writer</label>
                <Select 
                  defaultValue="gemini" 
                  onValueChange={(val) => onHandleInputChange('aiProvider', val)}
                >
                  <SelectTrigger className="w-full p-4 border border-gray-200 rounded-xl">
                    <SelectValue placeholder="Gemini 2.5 Flash" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="gemini">Gemini 2.5 Flash</SelectItem>
                    <SelectItem value="openai">ChatGPT (GPT-4o-mini)</SelectItem>
                    <SelectItem value="anthropic">Claude 3.5 Sonnet</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <label className="block text-sm font-bold text-gray-700 mb-2">Voice Narration Type</label>
                <Select 
                  defaultValue="free" 
                  onValueChange={(val) => onHandleInputChange('voiceProvider', val)}
                >
                  <SelectTrigger className="w-full p-4 border border-gray-200 rounded-xl">
                    <SelectValue placeholder="Free (Google Translate)" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="free">Free (Google Translate)</SelectItem>
                    <SelectItem value="gcp">Premium (Google Cloud TTS)</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            
            <Button className='mt-10 w-full py-6 text-lg cursor-pointer' onClick={onCreateClickHandler}>
              Generate Short Video
            </Button>
          </div>
        </>
      )}
      <CustomLoading loading={loading} status={statusText}/>

      {/* Beautiful Pop-up Alert Modal */}
      {alertConfig.isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm transition-opacity duration-300">
          <div className="relative w-full max-w-md rounded-3xl border border-gray-100 bg-white p-8 shadow-2xl transition-all duration-300 max-h-[90vh] overflow-y-auto">
            <div className="flex flex-col items-center text-center gap-4">
              <div className={`rounded-full p-4 ${
                alertConfig.type === 'error' ? 'bg-red-50 text-red-500' : 'bg-amber-50 text-amber-500'
              }`}>
                {alertConfig.type === 'error' ? (
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                ) : (
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10 animate-pulse" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                  </svg>
                )}
              </div>
              <h3 className="text-2xl font-black text-gray-900 leading-tight">{alertConfig.title}</h3>
              <p className="text-sm text-gray-500 leading-relaxed mt-1">{alertConfig.message}</p>
              
              <button
                onClick={() => setAlertConfig(prev => ({ ...prev, isOpen: false }))}
                className="mt-6 w-full bg-primary hover:bg-primary/95 text-white font-bold py-3.5 px-6 rounded-2xl shadow-lg shadow-primary/20 hover:shadow-primary/30 transition-all hover:scale-[1.02] cursor-pointer"
              >
                OK
              </button>
            </div>
          </div>
        </div>
      )}
   </div>
  )
}

export default CreateNew