import { NextResponse } from 'next/server';
import { GoogleGenAI } from '@google/genai';

export async function POST(req) {
  try {
    const { prompt, style } = await req.json();
    const apiKey = req.headers.get('x-gemini-key');

    if (!apiKey) {
      return NextResponse.json(
        { Error: 'Gemini API Key is required. Please configure it in Waffle Studio settings.' },
        { status: 400 }
      );
    }

    if (!prompt || prompt.trim() === '') {
      return NextResponse.json({ Error: 'Prompt content is required' }, { status: 400 });
    }

    // Blend style instructions into the prompt for Imagen
    const finalPrompt = style 
      ? `A short video scene, vertical format, style of ${style}. Description: ${prompt}` 
      : `A short video scene, vertical format. Description: ${prompt}`;

    console.log(`Sending image generation request for prompt: "${finalPrompt.substring(0, 50)}..."`);

    const ai = new GoogleGenAI({ apiKey });
    
    const response = await ai.models.generateImages({
      model: 'imagen-3.0-generate-002',
      prompt: finalPrompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/jpeg',
        aspectRatio: '9:16', // Vertical aspect ratio for short vertical videos
      }
    });

    if (!response?.generatedImages || response.generatedImages.length === 0) {
      throw new Error('No image was generated by the Imagen API');
    }

    const generatedImage = response.generatedImages[0];
    const imageBytes = generatedImage.image?.imageBytes;

    if (!imageBytes) {
      throw new Error('Image bytes content is missing in the response');
    }

    return NextResponse.json({ imageBytes });

  } catch (error) {
    console.error('Image Generation Route Error:', error);
    return NextResponse.json(
      { Error: error.message || 'Failed to generate image' },
      { status: error.status || 500 }
    );
  }
}
