import { NextResponse } from 'next/server';
import { GoogleGenAI } from '@google/genai';
import axios from 'axios';

export async function POST(req) {
  try {
    const { prompt, style } = await req.json();
    
    const provider = req.headers.get('x-image-provider') || 'gemini';
    const apiKey = req.headers.get('x-image-key') || req.headers.get('x-gemini-key') || (provider === 'gemini' ? process.env.GEMINI_API_KEY : process.env.OPENAI_API_KEY);

    if (!apiKey) {
      return NextResponse.json(
        { Error: `${provider === 'gemini' ? 'Gemini' : 'OpenAI'} API Key is required. Please configure it in Waffle Studio settings.` },
        { status: 400 }
      );
    }

    if (!prompt || prompt.trim() === '') {
      return NextResponse.json({ Error: 'Prompt content is required' }, { status: 400 });
    }

    // Blend style instructions into the prompt
    const finalPrompt = style 
      ? `A short video scene, vertical format, style of ${style}. Description: ${prompt}` 
      : `A short video scene, vertical format. Description: ${prompt}`;

    console.log(`Sending image generation request to ${provider.toUpperCase()} for prompt: "${finalPrompt.substring(0, 50)}..."`);

    let imageBytes = null;

    if (provider === 'openai') {
      // Call OpenAI DALL-E 3 API
      const response = await axios.post('https://api.openai.com/v1/images/generations', {
        model: 'dall-e-3',
        prompt: finalPrompt,
        n: 1,
        size: '1024x1792', // Portrait format for vertical short videos
        response_format: 'b64_json'
      }, {
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`
        }
      });

      imageBytes = response.data?.data?.[0]?.b64_json;
      if (!imageBytes) {
        throw new Error('No image was generated by the DALL-E API');
      }
    } else {
      // Default to Google Imagen 3
      const ai = new GoogleGenAI({ 
        apiKey,
        httpOptions: {
          apiVersion: 'v1'
        }
      });
      const response = await ai.models.generateImages({
        model: 'imagen-3.0-generate-002',
        prompt: finalPrompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/jpeg',
          aspectRatio: '9:16',
        }
      });

      if (!response?.generatedImages || response.generatedImages.length === 0) {
        throw new Error('No image was generated by the Imagen API');
      }

      imageBytes = response.generatedImages[0].image?.imageBytes;
      if (!imageBytes) {
        throw new Error('Image bytes content is missing in the response');
      }
    }

    return NextResponse.json({ imageBytes });

  } catch (error) {
    console.error('Image Generation Route Error:', error.response?.data || error.message);
    const errMsg = error.response?.data?.error?.message || error.message || 'Failed to generate image';
    return NextResponse.json(
      { Error: errMsg },
      { status: error.status || 500 }
    );
  }
}
